### ISSUE TITLE
How did you reverse-engineer the original software?

### ISSUE THREAD

**Issue by palmerj** [bentorkington/sf2ww#1]
Wow, I must say this looks like an exciting project, and many, many hours of work! Would you mind sharing how you went about reverse-engineering the M68k ROM code? Looking at the codebase, it seems like you were using a reverse engineering tool like ida pro. I guess this could be a massive series of blog posts in itself, but at least a couple of key things you did would be cool to hear about.

Thanks heaps for the contribution. SF2 is one of my favourite games of all time!

**Comment by bentorkington** [comment]
I didn't use IDA, just a basic m68k disassembly tool and a text editor. Ghidra was released relatively recently, and I've been working on some macros to help people disassemble other games which I'll hopefully release one day.
