### ISSUE TITLE
Autoconf build scripts need updating for building on Linux, Windows

### ISSUE THREAD

**Issue by xcom169** [bentorkington/sf2ww#2]
Can you please post build instructions for Ubuntu like cmake, or ./configure  ?

**Comment by bentorkington** [comment]
I made some progress on autotools building, on a new branch, `autotools-build`. It builds (on x86 and arm) and runs, but currently freezes as soon as a coin is inserted.

**Comment by bentorkington** [comment]
I replaced autotools with CMake. I don't have much experience with either of them, and CMake seemed the lesser of two evils if I had to learn one of them.

It's all done in one top-level `CMakeLists.txt` file as I couldn't yet figure out how to build the (messy) project structure with a `CMakeList.txt` in each subdirectory. If anyone can help with this I'd appreciate it.

**Comment by xcom169** [comment]
CMake worked well on my Arch Linux OS.  Makefile created 1 executable. Is
that right?

**Comment by bentorkington** [comment]
That's right. Check out the updated `README.md`, you'll need to generate `allroms.bin` and `sf2gfx.bin` and place them in the same directory as the executable and it should run.
