### ISSUE TITLE
Wrong animation label when crouch turn

### ISSUE THREAD

**Issue by bhrousseau** [bentorkington/sf2ww#3]
Hi Ben,

I think there is a wrong label in playerstate.c (line 1249) :                 CASetAnim1(ply, STATUS_TURN_AROUND);
it should be STATUS_CROUCH_TURN.

Thanks, making this c code available is very nice !
Do you think it is possible to publish the 68000 code that goes with this dissassembly in c ?
It would be easier to find such defects (easier also because i'm writing a 6809 version ;-)
Benoit Rousseau.

**Comment by fabiensanglard** [comment]
You should send a pull request for your bug fix.
As for adding disassembly to the repo, I don't think it would be legal.

**Comment by bentorkington** [comment]
fixed in #4 - belated thanks, @bhrousseau 

As Fabien says, I can't publish the 68k source here, I recommend using the Mame debugger in conjunction with code addresses sprinkled throughout the C code here
